export const brandsList = [
  { id: 1, name: "Apple" },
  { id: 2, name: "Samsung" },
  { id: 3, name: "Sony" },
  { id: 4, name: "Microsoft" },
  { id: 5, name: "HP" },
  { id: 6, name: "Dell" },
  { id: 7, name: "Nike" },
  { id: 8, name: "Adidas" },
  { id: 9, name: "Gucci" },
  { id: 10, name: "Prada" },
  { id: 11, name: "Chanel" },
  { id: 12, name: "Louis Vuitton" },
  { id: 13, name: "Rolex" },
  { id: 14, name: "Casio" },
  { id: 15, name: "Ray-Ban" },
  { id: 16, name: "Mercedes-Benz" },
  { id: 17, name: "BMW" },
  { id: 18, name: "Toyota" },
  { id: 19, name: "Honda" },
  { id: 20, name: "Philips" },
  { id: 21, name: "Canon" },
  { id: 22, name: "Nikon" },
  { id: 23, name: "Leica" },
  { id: 24, name: "Puma" },
  { id: 25, name: "Reebok" },
  { id: 26, name: "Under Armour" },
  { id: 27, name: "Fendi" },
  { id: 28, name: "Versace" },
  { id: 29, name: "Hermès" },
  { id: 30, name: "Tiffany & Co." },
];
