export const categoriesList = [
  { id: 1, name: "Smartphones" },
  { id: 2, name: "Laptops" },
  { id: 3, name: "Fragrances" },
  { id: 4, name: "Skincare" },
  { id: 5, name: "Groceries" },
  { id: 6, name: "Home decoration" },
  { id: 7, name: "Furniture" },
  { id: 8, name: "Tops" },
  { id: 9, name: "Womens dresses" },
  { id: 10, name: "Womens shoes" },
  { id: 11, name: "Mens shirts" },
  { id: 12, name: "Mens shoes" },
  { id: 13, name: "Mens watches" },
  { id: 14, name: "Womens watches" },
  { id: 15, name: "Womens bags" },
  { id: 16, name: "Womens jewellery" },
  { id: 17, name: "Sunglasses" },
  { id: 18, name: "Automotive" },
  { id: 19, name: "Motorcycle" },
  { id: 20, name: "Lighting" },
];
